"""
This type stub file was generated by pyright.
"""

import cadquery as cq
from typing import Tuple

def hypocycloid(t: float, r1: float, r2: float) -> Tuple[float, float]:
    ...

def epicycloid(t: float, r1: float, r2: float) -> Tuple[float, float]:
    ...

def gear(t: float, r1: float = ..., r2: float = ...) -> Tuple[float, float]:
    ...

def generate_geometry() -> cq.Workplane:
    ...

