"""
This type stub file was generated by pyright.
"""

from examples.spindle_assembly.clamp import Clamp

class Bracket:
    def __init__(self, *, width: float = ..., height: float = ..., thickness: float = ..., clamp: Clamp, tee_nut_spacing: float = ..., hole_diameter: float = ..., vslot_face_to_top_measurement: float = ...) -> None:
        ...
    


