"""
This type stub file was generated by pyright.
"""

class Clamp:
    def __init__(self, *, bolt_stickout: float = ..., bolt_thread: str = ..., bolt_spacing_x: float = ..., bolt_spacing_y: float = ..., x: float = ..., y: float = ..., z: float = ..., upper_x: float = ..., upper_y: float = ..., shoulder_outer_x: float = ..., shoulder_inner_x: float = ..., shoulder_delta_y: float = ..., hole_diameter: float = ..., hole_position_x: float = ..., hole_position_z: float = ...) -> None:
        ...
    


