"""
This type stub file was generated by pyright.
"""

class Spindle:
    def __init__(self, *, nut_length: float = ..., shaft_length: float = ..., bearing_cap_height: float = ..., body_clamp_end_offset: float = ...) -> None:
        ...
    


