"""
This type stub file was generated by pyright.
"""

class VSlot:
    def __init__(self, *, outer_x: float, outer_y: float, base_depth: float, c_beam_dxf_profile_loc: str = ..., slot_length: float) -> None:
        ...
    


